server.port=8080
spring.main.banner-mode=off
logging.level.com.vaadin=INFO
logging.level.com.wontlost=INFO

# vaadin.productionMode is controlled via -Pproduction Maven profile.
vaadin.launch-browser=false
